[I 02:40:29.652 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 02:40:30.467 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 02:40:30.467 NotebookApp] 0 active kernels 
[I 02:40:30.467 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8888/
[I 02:40:30.467 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 02:41:10.804 NotebookApp] 302 GET / (107.107.63.231) 0.80ms
[I 02:41:11.701 NotebookApp] 302 GET /tree? (107.107.63.231) 0.95ms
[I 02:41:18.746 NotebookApp] 302 POST /login?next=%2Ftree%3F (107.107.63.231) 2.69ms
[I 02:41:33.900 NotebookApp] Creating new notebook in 
[W 02:41:39.907 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170909024029 (107.107.63.231) 10.29ms referer=https://ec2-34-214-52-54.us-west-2.compute.amazonaws.com:8888/notebooks/Untitled.ipynb?kernel_name=python3
[I 02:41:40.024 NotebookApp] Kernel started: e8342d68-e92f-477f-b308-c5be3d0786cf
[I 02:41:40.766 NotebookApp] Adapting to protocol v5.1 for kernel e8342d68-e92f-477f-b308-c5be3d0786cf
[I 02:43:40.362 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 02:45:41.057 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 02:46:48.453 NotebookApp] Interrupted...
[I 02:46:48.453 NotebookApp] Shutting down kernels
[I 02:46:48.755 NotebookApp] Kernel shutdown: e8342d68-e92f-477f-b308-c5be3d0786cf
[I 02:47:48.530 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 02:47:48.530 NotebookApp] 0 active kernels 
[I 02:47:48.531 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8888/
[I 02:47:48.531 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 02:47:56.230 NotebookApp] Kernel started: bef2efd8-c5b6-4607-bedc-7543dd331bfd
[I 02:47:57.083 NotebookApp] Adapting to protocol v5.1 for kernel bef2efd8-c5b6-4607-bedc-7543dd331bfd
[I 02:49:56.720 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 02:51:56.782 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 02:53:59.256 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 02:54:47.060 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 02:54:52.489 NotebookApp] Creating new file in 
[I 02:55:29.670 NotebookApp] Adapting to protocol v5.1 for kernel bef2efd8-c5b6-4607-bedc-7543dd331bfd
[I 02:57:30.176 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 02:59:30.604 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /opt/conda/conda-bld/opencv_1491943970124/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7341
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /opt/conda/conda-bld/opencv_1491943970124/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7341
[I 03:01:30.722 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /opt/conda/conda-bld/opencv_1491943970124/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7341
[I 03:03:30.518 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 03:05:29.917 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 03:05:41.609 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 03:05:51.816 NotebookApp] Interrupted...
[I 03:05:51.816 NotebookApp] Shutting down kernels
[I 03:05:52.418 NotebookApp] Kernel shutdown: bef2efd8-c5b6-4607-bedc-7543dd331bfd
[I 23:00:02.141 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 23:00:02.943 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 23:00:02.943 NotebookApp] 0 active kernels 
[I 23:00:02.943 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8888/
[I 23:00:02.943 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 23:00:44.244 NotebookApp] 302 GET / (166.172.61.88) 0.63ms
[I 23:00:44.374 NotebookApp] 302 GET /tree? (166.172.61.88) 0.89ms
[W 23:00:53.338 NotebookApp] 401 POST /login?next=%2Ftree%3F (166.172.61.88) 1.59ms referer=https://ec2-34-210-140-192.us-west-2.compute.amazonaws.com:8888/login?next=%2Ftree%3F
[W 23:00:53.483 NotebookApp] 404 GET /apple-touch-icon-precomposed.png (166.172.61.88) 8.59ms referer=None
[W 23:00:53.631 NotebookApp] 404 GET /apple-touch-icon.png (166.172.61.88) 1.03ms referer=None
[W 23:00:54.006 NotebookApp] 404 GET /apple-touch-icon-precomposed.png (166.172.61.88) 1.37ms referer=None
[W 23:00:54.151 NotebookApp] 404 GET /apple-touch-icon.png (166.172.61.88) 1.35ms referer=None
[W 23:00:55.279 NotebookApp] 404 GET /apple-touch-icon-precomposed.png (166.172.61.88) 1.25ms referer=None
[W 23:00:55.407 NotebookApp] 404 GET /apple-touch-icon.png (166.172.61.88) 1.28ms referer=None
[W 23:00:55.521 NotebookApp] 401 POST /login?next=%2Ftree%3F (166.172.61.88) 1.33ms referer=https://ec2-34-210-140-192.us-west-2.compute.amazonaws.com:8888/login?next=%2Ftree%3F
[W 23:00:56.670 NotebookApp] 401 POST /login?next=%2Ftree%3F (166.172.61.88) 2.46ms referer=https://ec2-34-210-140-192.us-west-2.compute.amazonaws.com:8888/login?next=%2Ftree%3F
[W 23:00:56.965 NotebookApp] 404 GET /apple-touch-icon-precomposed.png (166.172.61.88) 1.03ms referer=None
[W 23:00:57.113 NotebookApp] 404 GET /apple-touch-icon.png (166.172.61.88) 1.04ms referer=None
[I 23:00:58.359 NotebookApp] 302 POST /login?next=%2Ftree%3F (166.172.61.88) 1.47ms
[W 23:01:06.815 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170910230002 (166.172.61.88) 3.40ms referer=https://ec2-34-210-140-192.us-west-2.compute.amazonaws.com:8888/notebooks/Vehicle_Steering_With_DenseNet.ipynb
[I 23:01:07.180 NotebookApp] Kernel started: 9e30b977-58c4-4cc7-9c11-c36365c84811
[I 23:01:07.926 NotebookApp] Adapting to protocol v5.1 for kernel 9e30b977-58c4-4cc7-9c11-c36365c84811
[I 23:03:09.261 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[W 23:13:32.264 NotebookApp] Replacing stale connection: 9e30b977-58c4-4cc7-9c11-c36365c84811:C29DDF38B6744ACDBF7EAE814E38B0AD
[I 23:13:32.656 NotebookApp] Adapting to protocol v5.1 for kernel 9e30b977-58c4-4cc7-9c11-c36365c84811
[W 23:35:32.658 NotebookApp] WebSocket ping timeout after 119863 ms.
[I 23:36:03.708 NotebookApp] The port 8888 is already in use, trying another port.
[I 23:36:03.716 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 23:36:03.716 NotebookApp] 0 active kernels 
[I 23:36:03.716 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8889/
[I 23:36:03.716 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 23:36:36.002 NotebookApp] 302 POST /login?next=%2Ftree%3F (166.172.61.88) 1.18ms
[W 23:36:42.521 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170910230002 (166.172.61.88) 1.25ms referer=https://52.10.94.211:8888/notebooks/Vehicle_Steering_With_DenseNet.ipynb
[I 23:36:43.817 NotebookApp] Adapting to protocol v5.1 for kernel 9e30b977-58c4-4cc7-9c11-c36365c84811
[I 23:37:25.484 NotebookApp] Interrupted...
[I 23:37:25.485 NotebookApp] Shutting down kernels
[W 23:43:31.772 NotebookApp] Replacing stale connection: 9e30b977-58c4-4cc7-9c11-c36365c84811:EDF5D1F71CE44A9DBEA0FFA90CA4D10D
[I 23:43:32.059 NotebookApp] Adapting to protocol v5.1 for kernel 9e30b977-58c4-4cc7-9c11-c36365c84811
[I 00:18:31.404 NotebookApp] The port 8888 is already in use, trying another port.
[I 00:18:31.412 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 00:18:31.412 NotebookApp] 0 active kernels 
[I 00:18:31.412 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8889/
[I 00:18:31.412 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 00:19:44.402 NotebookApp] Interrupted...
[I 00:19:44.403 NotebookApp] Shutting down kernels
[W 00:24:15.940 NotebookApp] SSL Error on 9 ('166.171.185.128', 55348): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 00:24:16.071 NotebookApp] SSL Error on 8 ('166.171.185.128', 3547): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 00:24:16.350 NotebookApp] SSL Error on 8 ('166.171.185.128', 29939): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 00:24:16.748 NotebookApp] SSL Error on 8 ('166.171.185.128', 11949): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 00:25:43.950 NotebookApp] SSL Error on 9 ('166.171.185.128', 46773): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 00:25:44.089 NotebookApp] SSL Error on 8 ('166.171.185.128', 1587): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 00:25:44.351 NotebookApp] SSL Error on 8 ('166.171.185.128', 42225): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[W 00:25:49.669 NotebookApp] SSL Error on 8 ('166.171.185.128', 57073): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)
[I 00:26:07.451 NotebookApp] 302 GET / (166.171.185.128) 0.47ms
[I 00:26:07.591 NotebookApp] 302 GET /tree? (166.171.185.128) 0.57ms
[I 00:26:20.422 NotebookApp] 302 POST /login?next=%2Ftree%3F (166.171.185.128) 1.09ms
[W 00:26:32.434 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170910230002 (166.171.185.128) 1.33ms referer=https://52.10.94.211:8888/notebooks/Vehicle_Steering_With_DenseNet.ipynb
[I 00:26:34.313 NotebookApp] Adapting to protocol v5.1 for kernel 9e30b977-58c4-4cc7-9c11-c36365c84811
[I 00:28:33.826 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 00:29:26.474 NotebookApp] The port 8888 is already in use, trying another port.
[I 00:29:26.492 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 00:29:26.492 NotebookApp] 0 active kernels 
[I 00:29:26.492 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8889/
[I 00:29:26.492 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 00:29:34.970 NotebookApp] 302 GET / (166.171.185.128) 0.44ms
[W 00:29:48.515 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170910230002 (166.171.185.128) 1.38ms referer=https://52.10.94.211:8888/notebooks/Vehicle_Steering_With_DenseNet.ipynb
[I 00:29:50.343 NotebookApp] Adapting to protocol v5.1 for kernel 9e30b977-58c4-4cc7-9c11-c36365c84811
[I 00:30:02.063 NotebookApp] Interrupted...
[I 00:30:02.064 NotebookApp] Shutting down kernels
[I 00:33:23.102 NotebookApp] The port 8888 is already in use, trying another port.
[I 00:33:23.112 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 00:33:23.112 NotebookApp] 0 active kernels 
[I 00:33:23.112 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8889/
[I 00:33:23.112 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 00:33:26.100 NotebookApp] 302 GET / (166.171.185.128) 0.47ms
[W 00:33:34.794 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170910230002 (166.171.185.128) 1.48ms referer=https://52.10.94.211:8888/notebooks/Vehicle_Steering_With_DenseNet.ipynb
[I 00:33:36.714 NotebookApp] Adapting to protocol v5.1 for kernel 9e30b977-58c4-4cc7-9c11-c36365c84811
[I 00:33:52.504 NotebookApp] Interrupted...
[I 00:33:52.504 NotebookApp] Shutting down kernels
[C 00:34:46.320 NotebookApp] received signal 15, stopping
[I 00:34:46.321 NotebookApp] Shutting down kernels
[I 00:34:46.422 NotebookApp] Kernel shutdown: 9e30b977-58c4-4cc7-9c11-c36365c84811
[I 01:04:57.771 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 01:04:57.772 NotebookApp] 0 active kernels 
[I 01:04:57.772 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8888/
[I 01:04:57.772 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 01:05:16.726 NotebookApp] 302 GET / (166.171.185.128) 0.76ms
[I 01:05:33.955 NotebookApp] Kernel started: 4918cd07-a419-46ee-856d-db3d356ff400
[I 01:05:35.209 NotebookApp] Adapting to protocol v5.1 for kernel 4918cd07-a419-46ee-856d-db3d356ff400
[I 01:07:34.616 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in ipp_cvtColor, file /opt/conda/conda-bld/opencv_1491943970124/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7341
[I 01:09:34.115 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 01:10:53.045 NotebookApp] Kernel started: 4df79d14-ade3-4471-9e1e-14ec4e97789a
[I 01:10:55.332 NotebookApp] Adapting to protocol v5.1 for kernel 4df79d14-ade3-4471-9e1e-14ec4e97789a
[I 01:13:02.592 NotebookApp] Adapting to protocol v5.1 for kernel 4918cd07-a419-46ee-856d-db3d356ff400
[W 01:19:32.593 NotebookApp] WebSocket ping timeout after 119815 ms.
[W 11:32:55.280 NotebookApp] SSL Error on 9 ('91.196.50.33', 49341): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 22:01:57.064 NotebookApp] SSL Error on 9 ('216.158.238.186', 65535): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 05:01:11.396 NotebookApp] SSL Error on 9 ('91.196.50.33', 46062): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:17:32.211 NotebookApp] SSL Error on 9 ('212.92.105.117', 50273): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:43:52.652 NotebookApp] SSL Error on 9 ('212.92.105.117', 52360): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 21:42:01.508 NotebookApp] SSL Error on 9 ('188.92.74.16', 427): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 01:07:24.130 NotebookApp] SSL Error on 9 ('91.196.50.33', 35005): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:13.691 NotebookApp] SSL Error on 9 ('122.228.210.156', 54007): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:14.245 NotebookApp] SSL Error on 9 ('122.228.210.156', 54536): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:14.801 NotebookApp] SSL Error on 9 ('122.228.210.156', 55205): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:15.353 NotebookApp] SSL Error on 9 ('122.228.210.156', 56251): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:15.904 NotebookApp] SSL Error on 9 ('122.228.210.156', 57084): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:16.493 NotebookApp] SSL Error on 9 ('122.228.210.156', 57720): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:17.044 NotebookApp] SSL Error on 9 ('122.228.210.156', 58561): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:17.605 NotebookApp] SSL Error on 9 ('122.228.210.156', 59179): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 06:20:18.156 NotebookApp] SSL Error on 9 ('122.228.210.156', 59684): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 15:45:39.566 NotebookApp] SSL Error on 9 ('196.52.43.53', 10000): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[W 21:04:47.415 NotebookApp] SSL Error on 9 ('91.196.50.33', 35764): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:748)
[C 21:05:54.104 NotebookApp] received signal 15, stopping
[I 21:05:54.105 NotebookApp] Shutting down kernels
[I 21:05:54.206 NotebookApp] Kernel shutdown: 4918cd07-a419-46ee-856d-db3d356ff400
[I 21:05:54.207 NotebookApp] Kernel shutdown: 4df79d14-ade3-4471-9e1e-14ec4e97789a
[I 18:59:05.169 NotebookApp] Serving notebooks from local directory: /home/ubuntu/ALVNS/Vehicle_Steering
[I 18:59:05.170 NotebookApp] 0 active kernels 
[I 18:59:05.170 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8888/
[I 18:59:05.170 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 19:01:31.129 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170922185904 (192.40.59.112) 13.58ms referer=https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888/notebooks/Vehicle_Steering_With_DenseNet.ipynb
[I 19:03:44.375 NotebookApp] Kernel started: 2132049e-4759-4cf6-aa01-fc44eba843a4
[I 19:03:45.905 NotebookApp] Adapting to protocol v5.1 for kernel 2132049e-4759-4cf6-aa01-fc44eba843a4
2017-09-22 19:04:20.964949: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-22 19:04:20.965015: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-22 19:04:20.965026: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-22 19:04:21.336956: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-22 19:04:21.337258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 3.94GiB
Free memory: 3.90GiB
2017-09-22 19:04:21.337287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-09-22 19:04:21.337297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-09-22 19:04:21.337310: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GRID K520, pci bus id: 0000:00:03.0)
2017-09-22 19:04:33.506644: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 3797 get requests, put_count=3770 evicted_count=1000 eviction_rate=0.265252 and unsatisfied allocation rate=0.296813
2017-09-22 19:04:33.506709: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
[W 19:05:15.906 NotebookApp] WebSocket ping timeout after 90000 ms.
[E 19:05:16.006 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:16.353 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:16.699 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:17.045 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:17.393 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:17.738 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:18.085 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:18.432 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:18.779 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:19.124 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:19.472 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:19.818 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:20.165 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:20.511 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:05:20.858 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108 (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=A6748AE939A1488289767BC1FA9E4108', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'pcDIbDH6xE/k259Abaq2rQ==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[I 19:05:41.432 NotebookApp] Adapting to protocol v5.1 for kernel 2132049e-4759-4cf6-aa01-fc44eba843a4
[I 19:07:59.538 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:11:28.305 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:11:39.313 NotebookApp] Kernel interrupted: 2132049e-4759-4cf6-aa01-fc44eba843a4
[I 19:12:34.049 NotebookApp] 302 GET / (192.40.59.112) 0.53ms
[I 19:12:51.342 NotebookApp] Adapting to protocol v5.1 for kernel 2132049e-4759-4cf6-aa01-fc44eba843a4
[I 19:13:26.104 NotebookApp] Kernel interrupted: 2132049e-4759-4cf6-aa01-fc44eba843a4
[I 19:13:46.439 NotebookApp] Kernel interrupted: 2132049e-4759-4cf6-aa01-fc44eba843a4
[I 19:13:55.996 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:14:06.859 NotebookApp] Adapting to protocol v5.1 for kernel 2132049e-4759-4cf6-aa01-fc44eba843a4
[I 19:14:19.212 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:14:26.433 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:15:19.198 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:18:28.621 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:20:09.670 NotebookApp] Adapting to protocol v5.1 for kernel 2132049e-4759-4cf6-aa01-fc44eba843a4
[I 19:24:23.679 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:29:57.533 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:35:41.109 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:36:37.607 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[I 19:41:09.776 NotebookApp] Saving file at /Vehicle_Steering_With_DenseNet.ipynb
[W 19:56:09.671 NotebookApp] WebSocket ping timeout after 119696 ms.
[E 19:56:09.880 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:10.228 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:10.577 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:10.924 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:11.271 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:11.619 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:11.967 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:12.314 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:12.662 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:13.010 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:13.357 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:13.705 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:14.052 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 19:56:14.400 NotebookApp] Uncaught exception GET /api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B (192.40.59.112)
    HTTPServerRequest(protocol='https', host='ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', method='GET', uri='/api/kernels/2132049e-4759-4cf6-aa01-fc44eba843a4/channels?session_id=CC525D1136B1480BB0E09C5C04CF120B', version='HTTP/1.1', remote_ip='192.40.59.112', headers={'Upgrade': 'websocket', 'Connection': 'Upgrade', 'Host': 'ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Origin': 'https://ec2-35-166-218-188.us-west-2.compute.amazonaws.com:8888', 'Cookie': 'username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888="2|1:0|10:1506106702|64:username-ec2-35-166-218-188-us-west-2-compute-amazonaws-com-8888|44:YmFiNWIyYTM4ZmQwNDA3MDkyMWJjOTUwNjI2OWQ5NzA=|1c53a5a7b690532dbb59491e5be8c4b02c84921c281a5a5ada658ca314b5ef74"; _xsrf=2|2e5bd9d4|4951bae078b62dea79dfd87531f72f35|1506106693', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Sec-Websocket-Key': 'zgcUJQkYjxJ+szfmqdnP9g==', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38'})
    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 392, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 258, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
2017-09-22 20:28:51.130962: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.47GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-09-22 20:28:52.021583: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.71GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
[C 20:55:15.498 NotebookApp] received signal 15, stopping
[I 20:55:15.499 NotebookApp] Shutting down kernels
[I 20:55:15.600 NotebookApp] Kernel shutdown: 2132049e-4759-4cf6-aa01-fc44eba843a4
